# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66ea23673cee23a51e0aef49301067c73a21769edc2a4bd6c6e48c4e3d539cbb2146afe8c89c0a3106e783df70400146e44593a14c2d63cba88c8cf1ec69061f

test:
  secret_key_base: e307e00bfacf4f7011bce2f64633e22e0bc8bfee5fa46a160ed6cc10cbdc79835c6433c639d71e15fc707e2eaa38829ee6c17d5b07c5207bc0737c544d4797f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
